name          'waveclaw-subscription_manager'
version       '1.3.2'
source        'https://github.com/waveclaw/puppet-subscription_manager'
author        'JD Powell <waveclaw@hotmail.com'
license       'Apache License, Version 2.0'
summary 'subscription_manager provider for Puppet'
description 'This module provides Custom Providers for RedHat Network Registering.'
project_page  'https://github.com/waveclaw/puppet-subscription_manager'

dependency 'adrien-boolean','>= 0.5.0'
